#https://docs.docker.com/compose/environment-variables/env-file/
#https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose#step-3-defining-services-with-docker-compose

services:
  nginx:
    image: nginx:dyeboa
    build: ./requirements/nginx/.
    container_name: nginx
    volumes:
      - wp:/var/www/html  
    networks:
      - network-inception
    env_file: .env
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:dyeboa
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    restart: always
    networks:
      - network-inception
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:dyeboa
    build: ./requirements/mariadb
    restart: always
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      - network-inception
    env_file: .env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]

networks:
  network-inception:
    driver: bridge

volumes: 
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/daaf/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/daaf/data/mariadb
      o: bind